// Generated by CoffeeScript 2.3.2
(function() {
  var dataFile;

  dataFile = './data/staffdata';

  module.exports = {
    dataCSV: `${dataFile}.csv`,
    dataJSON: `${dataFile}.json`,
    uonStartDate: '2005-09-01',
    uonHistoricalStartDate: '1927-01-01',
    dataDir: './data',
    libDir: './lib',
    outputDir: './out'
  };

}).call(this);
